allowBuilds:
  "@parcel/watcher": true
  esbuild: false
  simple-git-hooks: true
minimumReleaseAge: 0 # 小时
strictPeerDependencies: true
packages:
  - "packages/*"

# v10.x
onlyBuiltDependencies:
  - simple-git-hooks
